[package]
name = "aidl-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
line-col = { version = "0.2", features = ["grapheme-clusters"] }
peg = "0.7"
peg-macros = "0.7"
regex = "1.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
insta = { version = "1.8", features = ["redactions", "ron"] }
